name: Build and Deploy Quackbook

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout quackbook repository
        uses: actions/checkout@v4
        with:
          repository: andreitere/quackbook
          path: quackbook

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Build quackbook
        working-directory: ./quackbook
        run: |
          pnpm install
          pnpm build

      - name: Move dist folder
        run: |
          rm -rf public/quackbook
          mkdir -p public/quackbook
          cp -r quackbook/dist/* public/quackbook/

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add public/quackbook
          git status
          git commit -m "Update quackbook dist folder" || echo "No changes to commit"
          git push
